# Hopfield NN

In [443]:
import numpy as np

class NM:
    def __init__(self, L):
        self.weight_matrix = np.zeros((15, 15)) # set weight matrix
        self.L = L # sample for memory in asocial memory
        
    def train(self):
        for i, _ in enumerate(self.weight_matrix):
            for j, _  in enumerate(self.weight_matrix):
                if i != j:
                    for k, _  in enumerate(L):
                        self.weight_matrix[i][j] += self.L[k][j] * self.L[k][i]
                    
    def check(self, vector_x):
        assert vector_x.shape[0] == self.weight_matrix.shape[0], "Invalid size"
        y = np.ones(15)
        for i, _ in enumerate(self.weight_matrix):
            net = 0
            for j, _ in enumerate(self.weight_matrix):
                net += self.weight_matrix[j][i]*vector_x[j]
            if net > 0:
                y[i] = 1
            elif net < 0:
                y[i] = -1
                
            if y[i] < 0:
                print('   ', end = '')
            else:
                print(' X ', end = '')
            if (i+1) % 3 == 0:
                print('\n')


            
        
    
    def show_weight_matrix(self):
        print("W =\n", self.weight_matrix)

    def show_sample(self):
        print("L =\n", self.L)
        

In [444]:
W = np.array([])
L = np.array([[-1, 1, -1, 
               1,-1, -1,
               1, 1, -1,
               1,-1,  1,
              -1, 1, -1],#6, shape 3x5, linearized 15, accordingly weight matrix shape 15x15
            
            [ 1,  1, 1,
             -1, -1, 1,
             -1,  1,-1,
             -1,  1,-1,
             -1,  1,-1],#7
             
             
            [1, -1, -1,
             1, -1,  1,
             1, -1,  1,
             1,  1,  1,
            -1, -1,  1]]) #4

In [445]:
# pic = np.array([-1, 1, 1,
#                  1,-1,-1,
#                  1,-1,-1, 
#                  1, 1, 1, 
#                  1, 1, 1])
# pic = np.array(
#       [-1, 1, -1, 
#         1,-1, -1,
#         1, 1, -1,
#         1,-1,  1,
#        1, 1, 1])#6

pic = np.array(
            [1, -1, -1,
             1, -1,  1,
             1, -1,  1,
             1,  -1,  1,
            -1, 1,  1])#4

In [448]:
test = NM(L)
test.train()
test.show_weight_matrix()
test.show_sample()
print()
print("INPUT = ")
for i, value in enumerate(pic):
    if value < 0:
        print('   ', end = '')
    else:
        print(' X ', end = '')
    if (i+1) % 3 == 0:
        print('\n')
print()
print("U = ")
test.check(pic)

W =
 [[ 0. -1.  1. -1. -1.  3. -1. -1.  1. -1.  3. -1. -1. -1.  1.]
 [-1.  0.  1. -1. -1. -1. -1.  3. -3. -1. -1. -1. -1.  3. -3.]
 [ 1.  1.  0. -3.  1.  1. -3.  1. -1. -3.  1. -3.  1.  1. -1.]
 [-1. -1. -3.  0. -1. -1.  3. -1.  1.  3. -1.  3. -1. -1.  1.]
 [-1. -1.  1. -1.  0. -1. -1. -1.  1. -1. -1. -1.  3. -1.  1.]
 [ 3. -1.  1. -1. -1.  0. -1. -1.  1. -1.  3. -1. -1. -1.  1.]
 [-1. -1. -3.  3. -1. -1.  0. -1.  1.  3. -1.  3. -1. -1.  1.]
 [-1.  3.  1. -1. -1. -1. -1.  0. -3. -1. -1. -1. -1.  3. -3.]
 [ 1. -3. -1.  1.  1.  1.  1. -3.  0.  1.  1.  1.  1. -3.  3.]
 [-1. -1. -3.  3. -1. -1.  3. -1.  1.  0. -1.  3. -1. -1.  1.]
 [ 3. -1.  1. -1. -1.  3. -1. -1.  1. -1.  0. -1. -1. -1.  1.]
 [-1. -1. -3.  3. -1. -1.  3. -1.  1.  3. -1.  0. -1. -1.  1.]
 [-1. -1.  1. -1.  3. -1. -1. -1.  1. -1. -1. -1.  0. -1.  1.]
 [-1.  3.  1. -1. -1. -1. -1.  3. -3. -1. -1. -1. -1.  0. -3.]
 [ 1. -3. -1.  1.  1.  1.  1. -3.  3.  1.  1.  1.  1. -3.  0.]]
L =
 [[-1  1 -1  1 -1 -1  1  1 -1  1 -1  1 -1  1 