In [1]:
import tensorflow as tf
import datetime
import os
from tensorflow.keras import layers

In [2]:
str_contant = tf.constant('this is string')

In [3]:
print(tf.add(1,2))
print(tf.add([1,2], [3,4]))
print(tf.square(5))
print(tf.reduce_sum([1,2,3,4,5]))
print(tf.reduce_sum([[1,2,3], [4,5,6], [7,8,9]], axis = 1))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)
tf.Tensor([ 6 15 24], shape=(3,), dtype=int32)


In [4]:
x = tf.matmul([[2]], [[2,3]])

In [5]:
x

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[4, 6]], dtype=int32)>

## Numpy compatibility

In [6]:
import numpy as np

arr = np.ones([3,3])
tensor = tf.multiply(arr, 42)
tensor

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[42., 42., 42.],
       [42., 42., 42.],
       [42., 42., 42.]])>

In [7]:
print(np.add(tensor, 1))
tensor.numpy()

[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]


array([[42., 42., 42.],
       [42., 42., 42.],
       [42., 42., 42.]])

## GPU

In [8]:
print(tf.config.experimental.list_physical_devices())

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


In [9]:
if tf.config.experimental.list_physical_devices('GPU'):
    print('GPU is available')
    with tf.device("GPU:0"): #name of gpu device
        x = tf.random.uniform([1000,1000])
        assert x.device.endwith("GPU:0")
        x1 = x * x
else:
    x = tf.random.uniform([1000,1000])
    x1 = x * x    

## Datasets

In [10]:
ds_tensor = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])

In [11]:
for elem in ds_tensor:
    print(elem.numpy())

1
2
3
4
5
6


In [12]:
ds_tensor = ds_tensor.map(tf.square).shuffle(4).batch(2)

In [13]:
for i in ds_tensor:
    print(i)

tf.Tensor([ 1 16], shape=(2,), dtype=int32)
tf.Tensor([ 4 25], shape=(2,), dtype=int32)
tf.Tensor([36  9], shape=(2,), dtype=int32)


In [14]:
# create csv
import tempfile
_, name = tempfile.mkstemp()
with open(name, 'w+') as file:
    file.write("""line 1
    line 2
    line 3
    line 4
    line 5
    line 6
    line 7
    line 8
    line 9    """)

ds_file = tf.data.TextLineDataset(name)

In [15]:
ds_file = ds_file.batch(3)

In [16]:
for i in ds_file:
    print(i)

tf.Tensor([b'line 1' b'    line 2' b'    line 3'], shape=(3,), dtype=string)
tf.Tensor([b'    line 4' b'    line 5' b'    line 6'], shape=(3,), dtype=string)
tf.Tensor([b'    line 7' b'    line 8' b'    line 9    '], shape=(3,), dtype=string)


## Session

In [17]:
tf.compat.v1.disable_eager_execution()
const = tf.constant(1.0)

In [18]:
with tf.compat.v1.Session() as sess: # first way
    output = sess.run(const)
    print(output)

1.0


In [19]:
x = tf.constant([1,2,3,4,5])
y = tf.constant([6,7,8,9,10])

In [20]:
result = tf.multiply(x,y)
result

<tf.Tensor 'Mul:0' shape=(5,) dtype=int32>

In [21]:
sess = tf.compat.v1.Session() # second way
print(sess.run(result))
sess.close()

[ 6 14 24 36 50]


## Variables

In [22]:
a = tf.Variable(1, name='scalar')
b = tf.Variable([1,2,3], name='vector')
t_2 = tf.Variable([[1,2,3], [1,1,0], [1,0,1]], name='matrix')

print(a, a.get_shape())
print()
print(b, b.get_shape())
print()
print(t_2, t_2.get_shape())

<tf.Variable 'scalar:0' shape=() dtype=int32> ()

<tf.Variable 'vector:0' shape=(3,) dtype=int32> (3,)

<tf.Variable 'matrix:0' shape=(3, 3) dtype=int32> (3, 3)


In [23]:
x = tf.Variable(1)
y = tf.Variable(10)

op1 = tf.add(x,y) #sum

init = tf.compat.v1.variables_initializer([x, y], name='init')

with tf.compat.v1.Session() as sess:
    sess.run(init)
    print(sess.run(op1))

11


In [24]:
x = [[2]]
m = tf.matmul(x, x)

with tf.compat.v1.Session() as sess:
    sess.run(init)
    print(sess.run(op1))

11


## Placeholders

In [25]:
x = tf.compat.v1.placeholder(tf.float32, shape=[1024, 1024]) #place for variable

y = tf.matmul(x,x) # define operation

with tf.compat.v1.Session() as sess:
    rand_array = np.random.rand(1024, 1024)
    
    print(sess.run(y, feed_dict = {x: rand_array}))

[[263.3604  245.26892 263.04346 ... 253.80496 258.62463 249.07329]
 [272.35074 256.03973 279.96286 ... 264.80438 267.4665  267.59644]
 [250.07146 238.83566 255.4855  ... 246.5055  244.01212 243.69691]
 ...
 [259.07614 249.6696  268.4033  ... 255.83765 255.97946 249.19551]
 [267.7468  251.79054 271.07495 ... 253.68735 262.23676 258.95782]
 [257.15546 236.0312  261.01367 ... 249.39404 252.57635 249.80923]]


## Tensorboard

In [26]:
tf.compat.v1.reset_default_graph() # reset variables above

In [27]:
x = tf.constant(1.0, name='input')

w = tf.Variable(0.8, name='weight')

y = tf.math.multiply(w, x, name='output')

In [28]:
init = tf.compat.v1.global_variables_initializer()
sess1 = tf.compat.v1.Session()
sess1.run(init)

In [29]:
sess1.run(y)

0.8

In [30]:
%load_ext tensorboard

In [31]:
logdir = os.path.join('logs', datetime.datetime.now().strftime("%Y%m%d - %H%M%S"))
summary_writer = tf.compat.v1.summary.FileWriter(logdir, sess1.graph)

In [32]:
%tensorboard --logdir logs

In [33]:
sess1.close()

## Train model

In [112]:
tf.compat.v1.reset_default_graph()

In [113]:
inp = tf.constant([1.2, 3.0, -2.2])

weight = tf.Variable([1., 2., 3.], dtype=tf.float32)

out_true = tf.constant(0.)
out_pred = tf.reduce_sum(inp*weight)

loss = (out_pred - out_true)**2

init = tf.compat.v1.global_variables_initializer()

sess = tf.compat.v1.Session()

optim = tf.compat.v1.train.GradientDescentOptimizer(learning_rate = 0.025)

compute_grad = optim.compute_gradients(loss, var_list = [weight])

In [114]:
sess.run(init)
print(sess.run(out_pred))
print(sess.run(loss))

0.5999994
0.3599993


In [115]:
sess.run(compute_grad, feed_dict = {weight: [1.0, 1.0, 1.0]})

[(array([ 1.4399986,  3.5999966, -2.6399975], dtype=float32),
  array([1., 1., 1.], dtype=float32))]

In [116]:
# one step
sess.run(optim.apply_gradients(compute_grad))
print(sess.run(weight))
print(sess.run(out_pred))
print(sess.run(loss))

[0.96400005 1.9100001  3.066     ]
0.14160061
0.020050732


In [117]:
train_step = optim.minimize(loss)
for i in range(10):
    sess.run(train_step)
    print(f'Step: {i+1}, loss: {sess.run(loss)}, pred: {sess.run(out_pred)}')

Step: 1, loss: 0.0011167109478265047, pred: 0.0334172248840332
Step: 2, loss: 6.219546048669145e-05, pred: 0.007886409759521484
Step: 3, loss: 3.461901542323176e-06, pred: 0.0018606185913085938
Step: 4, loss: 1.9328672351548448e-07, pred: 0.00043964385986328125
Step: 5, loss: 1.080570655176416e-08, pred: 0.00010395050048828125
Step: 6, loss: 5.684341886080801e-10, pred: 2.384185791015625e-05
Step: 7, loss: 3.2741809263825417e-11, pred: 5.7220458984375e-06
Step: 8, loss: 2.0463630789890885e-12, pred: 1.430511474609375e-06
Step: 9, loss: 0.0, pred: 0.0
Step: 10, loss: 0.0, pred: 0.0


In [118]:
sess.run(out_pred)

0.0

In [119]:
# отслеживание обучение
summary_y = tf.compat.v1.summary.scalar('upd_out_pred', out_pred)
summary_t = tf.compat.v1.summary.scalar('upd_loss', loss)
merged = tf.compat.v1.summary.merge_all()

In [120]:
summary_writed = tf.compat.v1.summary.FileWriter('education')
sess.run(tf.compat.v1.global_variables_initializer())
for i in range(10):
    summary = sess.run(merged)
    summary_writer.add_summary(summary, i)
    sess.run(train_step)

In [121]:
%tensorboard --logdir education

Reusing TensorBoard on port 6008 (pid 1032), started 0:01:26 ago. (Use '!kill 1032' to kill it.)